---
  - block:
      - name: stop jenkins
        service:
          name: jenkins
          state: stopped

      - name: start jenkins
        service:
          name: jenkins
          state: started

      - name: restart jenkins
        service:
          name: jenkins
          state: restarted
    become: true